### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by pingplug** [sunoru/pokemon_only#1]
1. 字体在 Linux 系统上炸了，完全无法显示。
2. 在 Firefox 下人物无法移动，无论系统。

**Comment by pingplug** [comment]
字体在 Linux 的字体查看器里已经有问题了
![2016-06-06 09-32-32](https://cloud.githubusercontent.com/assets/6712475/15809782/e1d627f2-2bc9-11e6-964b-8544bd15a25c.png)
什么都没有。。。
看起来是字体文件的锅

**Comment by sunoru** [comment]
感谢反馈，昨天我已看到在留言板上的信息，其实网站刚上线后我也在身边人的电脑上发现过这个问题，打算今天下课后来研究。

实际上我也是一直在linux环境（Fedora 23，Gnome 3）下开发的，所以出现这个问题我还是蛮惊讶的，以及可能只是个很少见的问题…我暂时只能先建议你换个环境访问了:(

**Comment by sunoru** [comment]
可以问一下你使用的Linux是什么发行版吗？

**Comment by pingplug** [comment]
Arch Linux 64 位
Firefox 46.0.1
